#!/usr/bin/env python3
"""Install and validate repository-distributed Codex and Claude Code skills."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
USER_INVOKED = {
    "implement",
    "research-workflow",
    "to-spec",
    "to-tickets",
    "wayfinder",
}
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
CLAUDE_CONTROL_FILES = {".gitignore"}
CLAUDE_IGNORE_CONTENT = (
    "# Platform-native mappings are generated by scripts/bootstrap.\n"
    "*\n"
    "!.gitignore\n"
)


def skill_roots(root: Path = ROOT) -> tuple[Path, Path]:
    return root / ".agents" / "skills", root / ".claude" / "skills"


def expected_skills(root: Path = ROOT) -> list[str]:
    agents_root, _ = skill_roots(root)
    if not agents_root.is_dir():
        return []
    return sorted(
        path.name
        for path in agents_root.iterdir()
        if path.is_dir() and (path / "SKILL.md").is_file()
    )


def relative_target(name: str) -> str:
    return f"../../.agents/skills/{name}"


def read_frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter opener")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("missing YAML frontmatter closer")
    values: dict[str, object] = {}
    for raw in text[4:end].splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if ":" not in raw:
            raise ValueError(f"unsupported frontmatter line: {raw}")
        key, value = raw.split(":", 1)
        value = value.strip()
        if value in {"true", "false"}:
            values[key.strip()] = value == "true"
        else:
            values[key.strip()] = value.strip('"\'')
    return values


def read_openai_policy(path: Path) -> bool | None:
    if not path.is_file():
        return None
    match = re.search(r"^\s*allow_implicit_invocation:\s*(true|false)\s*$", path.read_text(encoding="utf-8"), re.MULTILINE)
    if not match:
        return None
    return match.group(1) == "true"


def validate_claude_mapping_boundary(root: Path = ROOT) -> list[str]:
    _, claude_root = skill_roots(root)
    ignore_path = claude_root / ".gitignore"
    try:
        if ignore_path.read_text(encoding="utf-8") != CLAUDE_IGNORE_CONTENT:
            return ["invalid-claude-mapping-ignore .claude/skills/.gitignore"]
    except OSError as exc:
        return [f"missing-claude-mapping-ignore {exc}"]

    result = subprocess.run(
        ["git", "ls-files", "--", ".claude/skills"],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if result.returncode:
        return [f"cannot-inspect-tracked-claude-mappings {result.stdout.strip()}"]
    tracked = {line for line in result.stdout.splitlines() if line}
    expected = {".claude/skills/.gitignore"}
    if tracked != expected:
        return [
            "tracked-claude-mapping-boundary "
            f"actual={','.join(sorted(tracked)) or 'NONE'} "
            "expected=.claude/skills/.gitignore_only"
        ]
    return []


def validate_skill_sources(root: Path = ROOT) -> list[str]:
    errors = validate_claude_mapping_boundary(root)
    agents_root, _ = skill_roots(root)
    names = expected_skills(root)
    if not names:
        return ["no-skills-found .agents/skills"]
    for name in names:
        if not NAME_RE.fullmatch(name):
            errors.append(f"invalid-skill-directory {name}")
            continue
        skill_dir = agents_root / name
        try:
            frontmatter = read_frontmatter(skill_dir / "SKILL.md")
        except (OSError, ValueError) as exc:
            errors.append(f"invalid-skill-frontmatter {name}: {exc}")
            continue
        if frontmatter.get("name") != name:
            errors.append(f"skill-name-mismatch {name}: {frontmatter.get('name')!r}")
        if not isinstance(frontmatter.get("description"), str) or not str(frontmatter["description"]).strip():
            errors.append(f"missing-skill-description {name}")
        claude_disabled = frontmatter.get("disable-model-invocation") is True
        codex_policy = read_openai_policy(skill_dir / "agents" / "openai.yaml")
        if name in USER_INVOKED:
            if not claude_disabled:
                errors.append(f"user-skill-claude-implicit-enabled {name}")
            if codex_policy is not False:
                errors.append(f"user-skill-codex-implicit-enabled {name}")
        elif claude_disabled or codex_policy is False:
            errors.append(f"support-skill-unexpectedly-user-only {name}")
    missing = sorted(USER_INVOKED - set(names))
    errors.extend(f"missing-user-invoked-skill {name}" for name in missing)
    return errors


def is_junction(path: Path) -> bool:
    checker = getattr(path, "is_junction", None)
    return bool(checker and checker())


def resolves_to(path: Path, target: Path) -> bool:
    try:
        return path.resolve(strict=True) == target.resolve(strict=True)
    except OSError:
        return False


def is_placeholder(path: Path, expected: str) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    try:
        return path.read_text(encoding="utf-8").strip() == expected
    except (OSError, UnicodeDecodeError):
        return False


def remove_replaceable_mapping(path: Path, expected: str) -> None:
    if path.is_symlink() or is_placeholder(path, expected):
        path.unlink()
        return
    if is_junction(path):
        os.rmdir(path)
        return
    raise RuntimeError(f"refusing to replace non-generated path: {path}")


def create_mapping(link: Path, target: Path, expected: str, platform: str | None = None) -> None:
    platform = platform or os.name
    if platform == "nt":
        command_environment = os.environ.copy()
        command_environment["PROJECT_SKILL_LINK"] = str(link)
        command_environment["PROJECT_SKILL_TARGET"] = str(target)
        result = subprocess.run(
            [
                "powershell.exe",
                "-NoLogo",
                "-NoProfile",
                "-NonInteractive",
                "-Command",
                "$ErrorActionPreference='Stop'; "
                "New-Item -ItemType Junction -Path $env:PROJECT_SKILL_LINK "
                "-Target $env:PROJECT_SKILL_TARGET | Out-Null",
            ],
            env=command_environment,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if result.returncode:
            raise RuntimeError(f"junction creation failed for {link}: {result.stdout.strip()}")
    else:
        os.symlink(expected, link, target_is_directory=True)


def install(root: Path = ROOT, platform: str | None = None) -> list[str]:
    errors = validate_skill_sources(root)
    if errors:
        return errors
    agents_root, claude_root = skill_roots(root)
    claude_root.mkdir(parents=True, exist_ok=True)
    expected_names = expected_skills(root)
    for name in expected_names:
        link = claude_root / name
        target = agents_root / name
        expected = relative_target(name)
        if (link.is_symlink() or link.exists()) and resolves_to(link, target):
            continue
        if link.is_symlink() or link.exists():
            try:
                remove_replaceable_mapping(link, expected)
            except RuntimeError as exc:
                errors.append(str(exc))
                continue
        try:
            create_mapping(link, target, expected, platform=platform)
        except (OSError, RuntimeError) as exc:
            errors.append(str(exc))
    extras = sorted(
        path.name
        for path in claude_root.iterdir()
        if path.name not in expected_names and path.name not in CLAUDE_CONTROL_FILES
    )
    errors.extend(f"unexpected-claude-skill-mapping {name}" for name in extras)
    return errors


def doctor(root: Path = ROOT) -> list[str]:
    errors = validate_skill_sources(root)
    agents_root, claude_root = skill_roots(root)
    names = expected_skills(root)
    if not claude_root.is_dir():
        errors.append("missing-claude-skills-directory .claude/skills")
        return errors
    for name in names:
        link = claude_root / name
        if not (link.is_symlink() or link.exists()):
            errors.append(f"missing-claude-skill-mapping {name}")
        elif not resolves_to(link, agents_root / name):
            errors.append(f"wrong-claude-skill-target {name}")
    extras = sorted(
        path.name
        for path in claude_root.iterdir()
        if path.name not in names and path.name not in CLAUDE_CONTROL_FILES
    )
    errors.extend(f"unexpected-claude-skill-mapping {name}" for name in extras)
    return errors


def validate_label_manifest(root: Path = ROOT) -> list[str]:
    path = root / ".agents" / "skills" / "research-workflow" / "references" / "github-labels.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"invalid-label-manifest {exc}"]
    errors: list[str] = []
    labels = payload.get("labels") if isinstance(payload, dict) else None
    if not isinstance(labels, list) or not labels:
        return ["invalid-label-manifest labels must be a non-empty list"]
    seen: set[str] = set()
    for index, label in enumerate(labels):
        if not isinstance(label, dict):
            errors.append(f"invalid-label-entry index={index}")
            continue
        name = label.get("name")
        color = label.get("color")
        description = label.get("description")
        if not isinstance(name, str) or not name:
            errors.append(f"invalid-label-name index={index}")
        elif name in seen:
            errors.append(f"duplicate-label-name {name}")
        else:
            seen.add(name)
        if not isinstance(color, str) or re.fullmatch(r"[0-9a-fA-F]{6}", color) is None:
            errors.append(f"invalid-label-color {name}")
        if not isinstance(description, str) or not description or len(description) > 100:
            errors.append(f"invalid-label-description {name}")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("install", "doctor"))
    args = parser.parse_args(argv)
    errors = install() if args.command == "install" else doctor()
    errors.extend(validate_label_manifest())
    if errors:
        print(f"skills {args.command}: FAILED", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(
        f"skills {args.command}: OK physical={len(expected_skills())} "
        f"claude_mappings={len(expected_skills())}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
